// brand.typ
// Shared design system for Argus Documents

#let brand_color = rgb("#39b54a") // Example green color

#let letter_head(body) = {
  set page(
    paper: "us-letter",
    margin: (x: 1cm, y: 2cm),
  )
  set text(font: "Roboto", size: 10pt)

  // Header
  place(top + left, dy: -1cm)[
    #text(weight: "bold", size: 14pt, fill: brand_color)[CHIMERA]
    #h(1fr)
    #text(fill: gray)[Universal Document Engine]
  ]
  
  line(length: 100%, stroke: 1pt + gray)
  v(1cm)
  
  body
  
  v(1fr)
  // Footer
  align(center)[
    #text(size: 8pt, fill: gray)[Generated by Chimera Platform]
  ]
}
